export const API_ENDPOINTS = {
  LOGIN: 'https://7k21oxn5gh.execute-api.us-east-2.amazonaws.com/dev/user/login',
  REGISTER: 'https://7k21oxn5gh.execute-api.us-east-2.amazonaws.com/dev/user/register',
  LOGOUT: 'api/logout',
  FORGET_PASSWORD: 'api/forget-password',
  CATEGORIES: 'api/categories.json',
  FEATURED_CATEGORIES: 'api/featured_categories.json',
  COLLECTIONS: 'api/collections.json',
  BRANDS: 'api/brands.json',
  // PRODUCTS: 'api/products.json',
  PRODUCTS: 'https://7k21oxn5gh.execute-api.us-east-2.amazonaws.com/dev/dog',
  FEATURED_PRODUCTS: 'api/featured_products.json',
  TOP_SELLER_PRODUCTS: 'api/products_top_seller.json',
  ON_SELLING_PRODUCTS: 'api/products_on_selling.json',
  PRODUCT: '../api/product.json',
  RELATED_PRODUCTS: '../api/related_products.json',
  BEST_SELLER_PRODUCTS: 'api/products_best_seller.json',
  // NEW_ARRIVAL_PRODUCTS: 'api/products_new_arrival.json',
  NEW_ARRIVAL_PRODUCTS: 'https://7k21oxn5gh.execute-api.us-east-2.amazonaws.com/dev/dog',
  FLASH_SALE_PRODUCTS: 'api/products_flash_sale.json',
  SHOPS: 'api/shops.json',
  SHOP: 'api/shop.json',
  SEARCH: '../api/search.json',
  ORDERS: '../../api/orders.json',
  ORDER: '../../api/order.json',
  ADOPT: 'https://7k21oxn5gh.execute-api.us-east-2.amazonaws.com/dev/dog/adopt',
};
